/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 incubator.gltf --transform
Author: Odlab (https://sketchfab.com/Odlab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/incubator-b0dfcacde6694dc4b37b8b05459f7d0f
Title: Incubator
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/incubator-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AttVerinA_low_blinn2_0.geometry} material={materials.blinn2} />
      <mesh geometry={nodes.VitreExt_low_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.Lampe_low_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/incubator-transformed.glb')
