/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 left.gltf --transform
Author: A9908244 (https://sketchfab.com/A9908244)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-incubator-63f6bee67df14292b8c9a952b568cc96
Title: Sci fi incubator
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/left-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Shell} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Stand} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Stand} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Stand} position={[0, 1.33, 0.03]} rotation={[0.63, 0, 0]} scale={[1, 1, 0.51]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Light.001']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Bottom_display} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Light} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Top_display} position={[0, 1.33, 0.03]} rotation={[0.63, 0, 0]} scale={[1, 1, 0.51]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Light} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Light} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Light} position={[0, 1.28, 0]} rotation={[0.63, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Pipes} position={[0.28, 0.63, -0.46]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Wires} position={[0.08, 0.12, -0.33]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Wires} position={[0.03, 0.1, -0.34]} />
    </group>
  )
}

useGLTF.preload('/left-transformed.glb')
